apiVersion: v1
kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsfun
  namespace: test
spec:
  selector:
    matchLabels:
      app: devopsfun
  replicas: 1
  template:
    metadata:
      labels:
        app: devopsfun
    spec:
      containers:
      - name: devopsfun
        image: ado22.azurecr.io/devopsfun:90
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: devopsfun-service
  namespace: test
spec:
  selector:
    app: devopsfun
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
