# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04



- task: HelmInstaller@0
  displayName: Install Helm
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true

- task: CmdLine@2
  displayName: add helm repo
  inputs:
    script: |
      helm repo add grafana https://grafana.github.io/helm-charts
      
      helm repo update

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Pay-As-You-Go (9f5e6f55-0b11-4062-9a61-94be3d06c950)'
    azureResourceGroup: 'ctlab'
    kubernetesCluster: 'AKS00'
    command: 'install'
    chartType: 'Name'
    chartName: 'grafana/grafana'
    releaseName: 'grafana'